# cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    # Let's Encrypt production API
    server: https://acme-v02.api.letsencrypt.org/directory
    email: user@example.com # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-dev-account-key
    solvers:
    - selector:
        dnsZones:
          - "example.com"  # Replace with your domain
      dns01:
        route53:
          region: eu-west-1  # Replace with your AWS region
          hostedZoneID: <your-hosted-zone-id>  # From Step 5